// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace LiquidFab.Savegame
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Building : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Building __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float X { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public int Kind { get { return __p.bb.GetInt(__p.bb_pos + 8); } }

  public static Offset<LiquidFab.Savegame.Building> CreateBuilding(FlatBufferBuilder builder, float X, float Y, int Kind) {
    builder.Prep(4, 12);
    builder.PutInt(Kind);
    builder.PutFloat(Y);
    builder.PutFloat(X);
    return new Offset<LiquidFab.Savegame.Building>(builder.Offset);
  }
}


}
