// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace LiquidFab.Savegame
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Tree : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Tree __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int X { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public int Y { get { return __p.bb.GetInt(__p.bb_pos + 4); } }
  public int Kind { get { return __p.bb.GetInt(__p.bb_pos + 8); } }
  public float Age { get { return __p.bb.GetFloat(__p.bb_pos + 12); } }

  public static Offset<LiquidFab.Savegame.Tree> CreateTree(FlatBufferBuilder builder, int X, int Y, int Kind, float Age) {
    builder.Prep(4, 16);
    builder.PutFloat(Age);
    builder.PutInt(Kind);
    builder.PutInt(Y);
    builder.PutInt(X);
    return new Offset<LiquidFab.Savegame.Tree>(builder.Offset);
  }
}


}
