// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SAVEFILE_LIQUIDFAB_SAVEGAME_H_
#define FLATBUFFERS_GENERATED_SAVEFILE_LIQUIDFAB_SAVEGAME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace LiquidFab {
namespace Savegame {

struct Tree;

struct Building;

struct Floater;

struct Savegame;
struct SavegameBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Tree FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t x_;
  int32_t y_;
  int32_t kind_;
  float age_;

 public:
  Tree()
      : x_(0),
        y_(0),
        kind_(0),
        age_(0) {
  }
  Tree(int32_t _x, int32_t _y, int32_t _kind, float _age)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        kind_(::flatbuffers::EndianScalar(_kind)),
        age_(::flatbuffers::EndianScalar(_age)) {
  }
  int32_t x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  int32_t y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  int32_t kind() const {
    return ::flatbuffers::EndianScalar(kind_);
  }
  float age() const {
    return ::flatbuffers::EndianScalar(age_);
  }
};
FLATBUFFERS_STRUCT_END(Tree, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Building FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  int32_t kind_;

 public:
  Building()
      : x_(0),
        y_(0),
        kind_(0) {
  }
  Building(float _x, float _y, int32_t _kind)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        kind_(::flatbuffers::EndianScalar(_kind)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  int32_t kind() const {
    return ::flatbuffers::EndianScalar(kind_);
  }
};
FLATBUFFERS_STRUCT_END(Building, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Floater FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  int32_t kind_;

 public:
  Floater()
      : x_(0),
        y_(0),
        kind_(0) {
  }
  Floater(float _x, float _y, int32_t _kind)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        kind_(::flatbuffers::EndianScalar(_kind)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  int32_t kind() const {
    return ::flatbuffers::EndianScalar(kind_);
  }
};
FLATBUFFERS_STRUCT_END(Floater, 12);

struct Savegame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SavegameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_TREES = 6,
    VT_FLOATERS = 8,
    VT_BUILDINGS = 10,
    VT_TERRAIN_LEVEL = 12,
    VT_TERRAIN_KIND = 14,
    VT_WATER_LEVEL = 16,
    VT_WATER_FLOW_X = 18,
    VT_WATER_FLOW_Y = 20,
    VT_SUB_WATER_LEVEL = 22,
    VT_SUB_FLOW_X = 24,
    VT_SUB_FLOW_Y = 26
  };
  int32_t version() const {
    return GetField<int32_t>(VT_VERSION, 0);
  }
  const ::flatbuffers::Vector<const LiquidFab::Savegame::Tree *> *trees() const {
    return GetPointer<const ::flatbuffers::Vector<const LiquidFab::Savegame::Tree *> *>(VT_TREES);
  }
  const ::flatbuffers::Vector<const LiquidFab::Savegame::Floater *> *floaters() const {
    return GetPointer<const ::flatbuffers::Vector<const LiquidFab::Savegame::Floater *> *>(VT_FLOATERS);
  }
  const ::flatbuffers::Vector<const LiquidFab::Savegame::Building *> *buildings() const {
    return GetPointer<const ::flatbuffers::Vector<const LiquidFab::Savegame::Building *> *>(VT_BUILDINGS);
  }
  const ::flatbuffers::Vector<float> *terrain_level() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_TERRAIN_LEVEL);
  }
  const ::flatbuffers::Vector<float> *terrain_kind() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_TERRAIN_KIND);
  }
  const ::flatbuffers::Vector<float> *water_level() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_WATER_LEVEL);
  }
  const ::flatbuffers::Vector<float> *water_flow_x() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_WATER_FLOW_X);
  }
  const ::flatbuffers::Vector<float> *water_flow_y() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_WATER_FLOW_Y);
  }
  const ::flatbuffers::Vector<float> *sub_water_level() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_SUB_WATER_LEVEL);
  }
  const ::flatbuffers::Vector<float> *sub_flow_x() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_SUB_FLOW_X);
  }
  const ::flatbuffers::Vector<float> *sub_flow_y() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_SUB_FLOW_Y);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_VERSION, 4) &&
           VerifyOffset(verifier, VT_TREES) &&
           verifier.VerifyVector(trees()) &&
           VerifyOffset(verifier, VT_FLOATERS) &&
           verifier.VerifyVector(floaters()) &&
           VerifyOffset(verifier, VT_BUILDINGS) &&
           verifier.VerifyVector(buildings()) &&
           VerifyOffset(verifier, VT_TERRAIN_LEVEL) &&
           verifier.VerifyVector(terrain_level()) &&
           VerifyOffset(verifier, VT_TERRAIN_KIND) &&
           verifier.VerifyVector(terrain_kind()) &&
           VerifyOffset(verifier, VT_WATER_LEVEL) &&
           verifier.VerifyVector(water_level()) &&
           VerifyOffset(verifier, VT_WATER_FLOW_X) &&
           verifier.VerifyVector(water_flow_x()) &&
           VerifyOffset(verifier, VT_WATER_FLOW_Y) &&
           verifier.VerifyVector(water_flow_y()) &&
           VerifyOffset(verifier, VT_SUB_WATER_LEVEL) &&
           verifier.VerifyVector(sub_water_level()) &&
           VerifyOffset(verifier, VT_SUB_FLOW_X) &&
           verifier.VerifyVector(sub_flow_x()) &&
           VerifyOffset(verifier, VT_SUB_FLOW_Y) &&
           verifier.VerifyVector(sub_flow_y()) &&
           verifier.EndTable();
  }
};

struct SavegameBuilder {
  typedef Savegame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_version(int32_t version) {
    fbb_.AddElement<int32_t>(Savegame::VT_VERSION, version, 0);
  }
  void add_trees(::flatbuffers::Offset<::flatbuffers::Vector<const LiquidFab::Savegame::Tree *>> trees) {
    fbb_.AddOffset(Savegame::VT_TREES, trees);
  }
  void add_floaters(::flatbuffers::Offset<::flatbuffers::Vector<const LiquidFab::Savegame::Floater *>> floaters) {
    fbb_.AddOffset(Savegame::VT_FLOATERS, floaters);
  }
  void add_buildings(::flatbuffers::Offset<::flatbuffers::Vector<const LiquidFab::Savegame::Building *>> buildings) {
    fbb_.AddOffset(Savegame::VT_BUILDINGS, buildings);
  }
  void add_terrain_level(::flatbuffers::Offset<::flatbuffers::Vector<float>> terrain_level) {
    fbb_.AddOffset(Savegame::VT_TERRAIN_LEVEL, terrain_level);
  }
  void add_terrain_kind(::flatbuffers::Offset<::flatbuffers::Vector<float>> terrain_kind) {
    fbb_.AddOffset(Savegame::VT_TERRAIN_KIND, terrain_kind);
  }
  void add_water_level(::flatbuffers::Offset<::flatbuffers::Vector<float>> water_level) {
    fbb_.AddOffset(Savegame::VT_WATER_LEVEL, water_level);
  }
  void add_water_flow_x(::flatbuffers::Offset<::flatbuffers::Vector<float>> water_flow_x) {
    fbb_.AddOffset(Savegame::VT_WATER_FLOW_X, water_flow_x);
  }
  void add_water_flow_y(::flatbuffers::Offset<::flatbuffers::Vector<float>> water_flow_y) {
    fbb_.AddOffset(Savegame::VT_WATER_FLOW_Y, water_flow_y);
  }
  void add_sub_water_level(::flatbuffers::Offset<::flatbuffers::Vector<float>> sub_water_level) {
    fbb_.AddOffset(Savegame::VT_SUB_WATER_LEVEL, sub_water_level);
  }
  void add_sub_flow_x(::flatbuffers::Offset<::flatbuffers::Vector<float>> sub_flow_x) {
    fbb_.AddOffset(Savegame::VT_SUB_FLOW_X, sub_flow_x);
  }
  void add_sub_flow_y(::flatbuffers::Offset<::flatbuffers::Vector<float>> sub_flow_y) {
    fbb_.AddOffset(Savegame::VT_SUB_FLOW_Y, sub_flow_y);
  }
  explicit SavegameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Savegame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Savegame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Savegame> CreateSavegame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t version = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const LiquidFab::Savegame::Tree *>> trees = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const LiquidFab::Savegame::Floater *>> floaters = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const LiquidFab::Savegame::Building *>> buildings = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> terrain_level = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> terrain_kind = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> water_level = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> water_flow_x = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> water_flow_y = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> sub_water_level = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> sub_flow_x = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> sub_flow_y = 0) {
  SavegameBuilder builder_(_fbb);
  builder_.add_sub_flow_y(sub_flow_y);
  builder_.add_sub_flow_x(sub_flow_x);
  builder_.add_sub_water_level(sub_water_level);
  builder_.add_water_flow_y(water_flow_y);
  builder_.add_water_flow_x(water_flow_x);
  builder_.add_water_level(water_level);
  builder_.add_terrain_kind(terrain_kind);
  builder_.add_terrain_level(terrain_level);
  builder_.add_buildings(buildings);
  builder_.add_floaters(floaters);
  builder_.add_trees(trees);
  builder_.add_version(version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Savegame> CreateSavegameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t version = 0,
    const std::vector<LiquidFab::Savegame::Tree> *trees = nullptr,
    const std::vector<LiquidFab::Savegame::Floater> *floaters = nullptr,
    const std::vector<LiquidFab::Savegame::Building> *buildings = nullptr,
    const std::vector<float> *terrain_level = nullptr,
    const std::vector<float> *terrain_kind = nullptr,
    const std::vector<float> *water_level = nullptr,
    const std::vector<float> *water_flow_x = nullptr,
    const std::vector<float> *water_flow_y = nullptr,
    const std::vector<float> *sub_water_level = nullptr,
    const std::vector<float> *sub_flow_x = nullptr,
    const std::vector<float> *sub_flow_y = nullptr) {
  auto trees__ = trees ? _fbb.CreateVectorOfStructs<LiquidFab::Savegame::Tree>(*trees) : 0;
  auto floaters__ = floaters ? _fbb.CreateVectorOfStructs<LiquidFab::Savegame::Floater>(*floaters) : 0;
  auto buildings__ = buildings ? _fbb.CreateVectorOfStructs<LiquidFab::Savegame::Building>(*buildings) : 0;
  auto terrain_level__ = terrain_level ? _fbb.CreateVector<float>(*terrain_level) : 0;
  auto terrain_kind__ = terrain_kind ? _fbb.CreateVector<float>(*terrain_kind) : 0;
  auto water_level__ = water_level ? _fbb.CreateVector<float>(*water_level) : 0;
  auto water_flow_x__ = water_flow_x ? _fbb.CreateVector<float>(*water_flow_x) : 0;
  auto water_flow_y__ = water_flow_y ? _fbb.CreateVector<float>(*water_flow_y) : 0;
  auto sub_water_level__ = sub_water_level ? _fbb.CreateVector<float>(*sub_water_level) : 0;
  auto sub_flow_x__ = sub_flow_x ? _fbb.CreateVector<float>(*sub_flow_x) : 0;
  auto sub_flow_y__ = sub_flow_y ? _fbb.CreateVector<float>(*sub_flow_y) : 0;
  return LiquidFab::Savegame::CreateSavegame(
      _fbb,
      version,
      trees__,
      floaters__,
      buildings__,
      terrain_level__,
      terrain_kind__,
      water_level__,
      water_flow_x__,
      water_flow_y__,
      sub_water_level__,
      sub_flow_x__,
      sub_flow_y__);
}

}  // namespace Savegame
}  // namespace LiquidFab

#endif  // FLATBUFFERS_GENERATED_SAVEFILE_LIQUIDFAB_SAVEGAME_H_
