namespace LiquidFab.Savegame;

struct Tree {
    x:int;
    y:int;
    kind:int;
    age:float;
}

struct Building {
	x:float;
	y:float;
	z:float;
	anga:float;
	angb:float;
	angc:float;
	kind:int;
}

struct Floater {
	x:float;
	y:float;
	z:float;
	kind:int;
}

table Savegame {
    version: int;
    trees: [Tree];
	floaters: [Floater];
	buildings: [Building];
	terrain_level: [float];
	terrain_kind: [float];
	water_level: [float];
	water_flow_x: [float];
	water_flow_y: [float];
	sub_water_level: [float];
	sub_flow_x: [float];
	sub_flow_y: [float];
}
