// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace LiquidFab.Savegame
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Tree : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Tree __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int X { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public int Y { get { return __p.bb.GetInt(__p.bb_pos + 4); } }
  public int Kind { get { return __p.bb.GetInt(__p.bb_pos + 8); } }
  public float Age { get { return __p.bb.GetFloat(__p.bb_pos + 12); } }

  public static Offset<LiquidFab.Savegame.Tree> CreateTree(FlatBufferBuilder builder, int X, int Y, int Kind, float Age) {
    builder.Prep(4, 16);
    builder.PutFloat(Age);
    builder.PutInt(Kind);
    builder.PutInt(Y);
    builder.PutInt(X);
    return new Offset<LiquidFab.Savegame.Tree>(builder.Offset);
  }
}

public struct WaterPump : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public WaterPump __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int X { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public int Y { get { return __p.bb.GetInt(__p.bb_pos + 4); } }
  public float FuelLevel { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }
  public int Logs { get { return __p.bb.GetInt(__p.bb_pos + 12); } }

  public static Offset<LiquidFab.Savegame.WaterPump> CreateWaterPump(FlatBufferBuilder builder, int X, int Y, float FuelLevel, int Logs) {
    builder.Prep(4, 16);
    builder.PutInt(Logs);
    builder.PutFloat(FuelLevel);
    builder.PutInt(Y);
    builder.PutInt(X);
    return new Offset<LiquidFab.Savegame.WaterPump>(builder.Offset);
  }
}

public struct Savegame : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static Savegame GetRootAsSavegame(ByteBuffer _bb) { return GetRootAsSavegame(_bb, new Savegame()); }
  public static Savegame GetRootAsSavegame(ByteBuffer _bb, Savegame obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Savegame __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Version { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public LiquidFab.Savegame.Tree? Trees(int j) { int o = __p.__offset(6); return o != 0 ? (LiquidFab.Savegame.Tree?)(new LiquidFab.Savegame.Tree()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int TreesLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public LiquidFab.Savegame.WaterPump? WaterPumps(int j) { int o = __p.__offset(8); return o != 0 ? (LiquidFab.Savegame.WaterPump?)(new LiquidFab.Savegame.WaterPump()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int WaterPumpsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public float TerrainLevel(int j) { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(__p.__vector(o) + j * 4) : (float)0; }
  public int TerrainLevelLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<float> GetTerrainLevelBytes() { return __p.__vector_as_span<float>(10, 4); }
#else
  public ArraySegment<byte>? GetTerrainLevelBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public float[] GetTerrainLevelArray() { return __p.__vector_as_array<float>(10); }
  public float TerrainKind(int j) { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(__p.__vector(o) + j * 4) : (float)0; }
  public int TerrainKindLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<float> GetTerrainKindBytes() { return __p.__vector_as_span<float>(12, 4); }
#else
  public ArraySegment<byte>? GetTerrainKindBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public float[] GetTerrainKindArray() { return __p.__vector_as_array<float>(12); }
  public float WaterLevel(int j) { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(__p.__vector(o) + j * 4) : (float)0; }
  public int WaterLevelLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<float> GetWaterLevelBytes() { return __p.__vector_as_span<float>(14, 4); }
#else
  public ArraySegment<byte>? GetWaterLevelBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public float[] GetWaterLevelArray() { return __p.__vector_as_array<float>(14); }
  public float WaterFlowX(int j) { int o = __p.__offset(16); return o != 0 ? __p.bb.GetFloat(__p.__vector(o) + j * 4) : (float)0; }
  public int WaterFlowXLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<float> GetWaterFlowXBytes() { return __p.__vector_as_span<float>(16, 4); }
#else
  public ArraySegment<byte>? GetWaterFlowXBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public float[] GetWaterFlowXArray() { return __p.__vector_as_array<float>(16); }
  public float WaterFlowY(int j) { int o = __p.__offset(18); return o != 0 ? __p.bb.GetFloat(__p.__vector(o) + j * 4) : (float)0; }
  public int WaterFlowYLength { get { int o = __p.__offset(18); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<float> GetWaterFlowYBytes() { return __p.__vector_as_span<float>(18, 4); }
#else
  public ArraySegment<byte>? GetWaterFlowYBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public float[] GetWaterFlowYArray() { return __p.__vector_as_array<float>(18); }
  public float SubWaterLevel(int j) { int o = __p.__offset(20); return o != 0 ? __p.bb.GetFloat(__p.__vector(o) + j * 4) : (float)0; }
  public int SubWaterLevelLength { get { int o = __p.__offset(20); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<float> GetSubWaterLevelBytes() { return __p.__vector_as_span<float>(20, 4); }
#else
  public ArraySegment<byte>? GetSubWaterLevelBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public float[] GetSubWaterLevelArray() { return __p.__vector_as_array<float>(20); }
  public float SubFlowX(int j) { int o = __p.__offset(22); return o != 0 ? __p.bb.GetFloat(__p.__vector(o) + j * 4) : (float)0; }
  public int SubFlowXLength { get { int o = __p.__offset(22); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<float> GetSubFlowXBytes() { return __p.__vector_as_span<float>(22, 4); }
#else
  public ArraySegment<byte>? GetSubFlowXBytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public float[] GetSubFlowXArray() { return __p.__vector_as_array<float>(22); }
  public float SubFlowY(int j) { int o = __p.__offset(24); return o != 0 ? __p.bb.GetFloat(__p.__vector(o) + j * 4) : (float)0; }
  public int SubFlowYLength { get { int o = __p.__offset(24); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<float> GetSubFlowYBytes() { return __p.__vector_as_span<float>(24, 4); }
#else
  public ArraySegment<byte>? GetSubFlowYBytes() { return __p.__vector_as_arraysegment(24); }
#endif
  public float[] GetSubFlowYArray() { return __p.__vector_as_array<float>(24); }

  public static Offset<LiquidFab.Savegame.Savegame> CreateSavegame(FlatBufferBuilder builder,
      int version = 0,
      VectorOffset treesOffset = default(VectorOffset),
      VectorOffset water_pumpsOffset = default(VectorOffset),
      VectorOffset terrain_levelOffset = default(VectorOffset),
      VectorOffset terrain_kindOffset = default(VectorOffset),
      VectorOffset water_levelOffset = default(VectorOffset),
      VectorOffset water_flow_xOffset = default(VectorOffset),
      VectorOffset water_flow_yOffset = default(VectorOffset),
      VectorOffset sub_water_levelOffset = default(VectorOffset),
      VectorOffset sub_flow_xOffset = default(VectorOffset),
      VectorOffset sub_flow_yOffset = default(VectorOffset)) {
    builder.StartTable(11);
    Savegame.AddSubFlowY(builder, sub_flow_yOffset);
    Savegame.AddSubFlowX(builder, sub_flow_xOffset);
    Savegame.AddSubWaterLevel(builder, sub_water_levelOffset);
    Savegame.AddWaterFlowY(builder, water_flow_yOffset);
    Savegame.AddWaterFlowX(builder, water_flow_xOffset);
    Savegame.AddWaterLevel(builder, water_levelOffset);
    Savegame.AddTerrainKind(builder, terrain_kindOffset);
    Savegame.AddTerrainLevel(builder, terrain_levelOffset);
    Savegame.AddWaterPumps(builder, water_pumpsOffset);
    Savegame.AddTrees(builder, treesOffset);
    Savegame.AddVersion(builder, version);
    return Savegame.EndSavegame(builder);
  }

  public static void StartSavegame(FlatBufferBuilder builder) { builder.StartTable(11); }
  public static void AddVersion(FlatBufferBuilder builder, int version) { builder.AddInt(0, version, 0); }
  public static void AddTrees(FlatBufferBuilder builder, VectorOffset treesOffset) { builder.AddOffset(1, treesOffset.Value, 0); }
  public static void StartTreesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 4); }
  public static void AddWaterPumps(FlatBufferBuilder builder, VectorOffset waterPumpsOffset) { builder.AddOffset(2, waterPumpsOffset.Value, 0); }
  public static void StartWaterPumpsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 4); }
  public static void AddTerrainLevel(FlatBufferBuilder builder, VectorOffset terrainLevelOffset) { builder.AddOffset(3, terrainLevelOffset.Value, 0); }
  public static VectorOffset CreateTerrainLevelVector(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddFloat(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateTerrainLevelVectorBlock(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTerrainLevelVectorBlock(FlatBufferBuilder builder, ArraySegment<float> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTerrainLevelVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<float>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartTerrainLevelVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddTerrainKind(FlatBufferBuilder builder, VectorOffset terrainKindOffset) { builder.AddOffset(4, terrainKindOffset.Value, 0); }
  public static VectorOffset CreateTerrainKindVector(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddFloat(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateTerrainKindVectorBlock(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTerrainKindVectorBlock(FlatBufferBuilder builder, ArraySegment<float> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTerrainKindVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<float>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartTerrainKindVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddWaterLevel(FlatBufferBuilder builder, VectorOffset waterLevelOffset) { builder.AddOffset(5, waterLevelOffset.Value, 0); }
  public static VectorOffset CreateWaterLevelVector(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddFloat(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateWaterLevelVectorBlock(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateWaterLevelVectorBlock(FlatBufferBuilder builder, ArraySegment<float> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateWaterLevelVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<float>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartWaterLevelVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddWaterFlowX(FlatBufferBuilder builder, VectorOffset waterFlowXOffset) { builder.AddOffset(6, waterFlowXOffset.Value, 0); }
  public static VectorOffset CreateWaterFlowXVector(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddFloat(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateWaterFlowXVectorBlock(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateWaterFlowXVectorBlock(FlatBufferBuilder builder, ArraySegment<float> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateWaterFlowXVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<float>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartWaterFlowXVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddWaterFlowY(FlatBufferBuilder builder, VectorOffset waterFlowYOffset) { builder.AddOffset(7, waterFlowYOffset.Value, 0); }
  public static VectorOffset CreateWaterFlowYVector(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddFloat(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateWaterFlowYVectorBlock(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateWaterFlowYVectorBlock(FlatBufferBuilder builder, ArraySegment<float> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateWaterFlowYVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<float>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartWaterFlowYVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddSubWaterLevel(FlatBufferBuilder builder, VectorOffset subWaterLevelOffset) { builder.AddOffset(8, subWaterLevelOffset.Value, 0); }
  public static VectorOffset CreateSubWaterLevelVector(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddFloat(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateSubWaterLevelVectorBlock(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSubWaterLevelVectorBlock(FlatBufferBuilder builder, ArraySegment<float> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSubWaterLevelVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<float>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartSubWaterLevelVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddSubFlowX(FlatBufferBuilder builder, VectorOffset subFlowXOffset) { builder.AddOffset(9, subFlowXOffset.Value, 0); }
  public static VectorOffset CreateSubFlowXVector(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddFloat(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateSubFlowXVectorBlock(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSubFlowXVectorBlock(FlatBufferBuilder builder, ArraySegment<float> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSubFlowXVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<float>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartSubFlowXVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddSubFlowY(FlatBufferBuilder builder, VectorOffset subFlowYOffset) { builder.AddOffset(10, subFlowYOffset.Value, 0); }
  public static VectorOffset CreateSubFlowYVector(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddFloat(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateSubFlowYVectorBlock(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSubFlowYVectorBlock(FlatBufferBuilder builder, ArraySegment<float> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSubFlowYVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<float>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartSubFlowYVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<LiquidFab.Savegame.Savegame> EndSavegame(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<LiquidFab.Savegame.Savegame>(o);
  }
}


static public class SavegameVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Version*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 6 /*Trees*/, 16 /*LiquidFab.Savegame.Tree*/, false)
      && verifier.VerifyVectorOfData(tablePos, 8 /*WaterPumps*/, 16 /*LiquidFab.Savegame.WaterPump*/, false)
      && verifier.VerifyVectorOfData(tablePos, 10 /*TerrainLevel*/, 4 /*float*/, false)
      && verifier.VerifyVectorOfData(tablePos, 12 /*TerrainKind*/, 4 /*float*/, false)
      && verifier.VerifyVectorOfData(tablePos, 14 /*WaterLevel*/, 4 /*float*/, false)
      && verifier.VerifyVectorOfData(tablePos, 16 /*WaterFlowX*/, 4 /*float*/, false)
      && verifier.VerifyVectorOfData(tablePos, 18 /*WaterFlowY*/, 4 /*float*/, false)
      && verifier.VerifyVectorOfData(tablePos, 20 /*SubWaterLevel*/, 4 /*float*/, false)
      && verifier.VerifyVectorOfData(tablePos, 22 /*SubFlowX*/, 4 /*float*/, false)
      && verifier.VerifyVectorOfData(tablePos, 24 /*SubFlowY*/, 4 /*float*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
