#pragma kernel CSMain

struct Particle
{
    float2 position;
    int2 speed;
    int bond1, bond2;
    int kind;
};

RWStructuredBuffer<Particle> Particles;
StructuredBuffer<float> attraction; // nColors x nColors
int textureSize;
int nColors;

#define REACTIONDIST 10
#define MINDIST 15
#define MAXDIST 150
#define PEAKDIST 25
#define PEAKFORCE 0.05

float2 calculateForce(float difX, float difY, float factor, float sDist)
{
    if (sDist == 0)
    {
        sDist = 1;
        difX = 1;
        difY = 0;
    }
    float dist = sqrt(sDist);
    float force = 0;
    if (dist < MINDIST)
    {
        force = 0.3 * pow((MINDIST - dist) / MINDIST, 2);
    }
    else if (dist < PEAKDIST)
    {
        force = -factor * PEAKFORCE * (dist - MINDIST) / (PEAKDIST - MINDIST);
    }
    else if (dist < MAXDIST)
    {
        float factor2 = (dist - PEAKDIST) / (MAXDIST - PEAKDIST);
        force = -factor * PEAKFORCE * (1 - factor2 * factor2);
    }
    return float2(0.02 * force * difX / dist, 0.02 * force * difY / dist);
}

float2 springForce(float difX, float difY, float sDist)
{
    float dist = sqrt(sDist);
    float force = (MINDIST - dist) / MINDIST;
    return float2(0.014 * force * difX / dist, 0.014 * force * difY / dist);
}

float wrappedDiff(float p1, float p2)
{
    float r = p1 - p2;
    float c1 = p1 - p2 + 2048;
    float c2 = p1 - p2 - 2048;
    if (abs(c1) < abs(r))
        r = c1;
    if (abs(c2) < abs(r))
        r = c2;
    return r;
}

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x == id.y)
        return;
    Particle p1 = Particles[id.x];
    Particle p2 = Particles[id.y];
    float difX = wrappedDiff(p1.position.x, p2.position.x);
    float difY = wrappedDiff(p1.position.y, p2.position.y);
    float dist = difX * difX + difY * difY;
    float v = attraction[p1.kind * nColors + p2.kind];
    float2 force = float2(0, 0);
    if (p1.bond1 == id.y || p1.bond2 == id.y)
    {
        force = springForce(difX, difY, dist);
    }
    else if (p1.kind == 0 && p2.kind == 0 && p1.bond1 == -1 && p2.bond2 == -1 && dist < REACTIONDIST * REACTIONDIST)
    {
        Particles[id.x].bond1 = id.y;
        Particles[id.y].bond2 = id.x;
    }
    else
    {
        force = calculateForce(difX, difY, v, dist);
    }
    InterlockedAdd(Particles[id.x].speed.x, (int) (force.x * 32768));
    InterlockedAdd(Particles[id.x].speed.y, (int) (force.y * 32768));
}
