#pragma kernel CSMain

struct Particle
{
    float2 position;
    float2 speed;
    int kind;
};

RWStructuredBuffer<Particle> Particles;
StructuredBuffer<float> attraction; // nColors x nColors
int textureSize;
int nColors;

#define MINDIST 5
#define MAXDIST 150
#define PEAKDIST 20

float2 calculateForce(float difX, float difY, float factor, float sDist, Particle p1, Particle p2)
{
    float dist = sqrt(sDist);
    float force = 0;
    if (dist < MINDIST)
    {
        force = -0.03 * (dist - MINDIST);
    }
    else if (dist < PEAKDIST)
    {
        force = factor * 0.02 * (dist - MINDIST);
    }
    else if (dist < MAXDIST)
    {
        force = factor * 0.02 * (PEAKDIST - MINDIST) - 0.001 * (dist - PEAKDIST);
    }
    return float2(0.002 * force * difX / dist, 0.002 * force * difY / dist);
}

float wrappedDiff(float p1, float p2)
{
    float r = p1 - p2;
    float c1 = p1 - p2 + 2048;
    float c2 = p1 - p2 - 2048;
    if (abs(c1) < abs(r))
        r = c1;
    if (abs(c2) < abs(r))
        r = c2;
    return r;
}

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x == id.y)
        return;
    Particle p1 = Particles[id.x];
    Particle p2 = Particles[id.y];
    float difX = wrappedDiff(p1.position.x, p2.position.x);
    float difY = wrappedDiff(p1.position.y, p2.position.y);
    float dist = difX * difX + difY * difY;
    float v = attraction[p1.kind * nColors + p2.kind];
    float2 force = calculateForce(difX, difY, v, dist, p1, p2);
    Particles[id.x].speed += force;
}
