// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
RWTexture2D<float4> Input;
float4 _Time;

float random_value(uint id)
{
    uint seed = id * 1664525u + 1013904223u;
    return float(seed & 0x00FFFFFFu) / float(0x01000000u);
}

bool yellow_pixel(RWTexture2D<float4> tex, float2 pos)
{
    if (pos.x > 2047 || pos.y > 2047)
        return false;
    if (tex[pos].r == tex[pos].g && tex[pos].g != 0)
        return true;
    return false;
}

float yellow_color(RWTexture2D<float4> tex, float2 pos)
{
    if (!yellow_pixel(tex, pos))
        return 0;
    return tex[pos].r;
}

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float4 green = float4(0, 1, 0, 1);
    float4 red = float4(1, 0, 0, 1);
    float4 yellow = float4(1, 1, 0, 1);
    uint rand_seed = uint(10000 * _Time.x) ^ uint(id.x * 1000.0) ^ (uint(id.y * 1000.0) << 16);
    if (id.x == 0)
    {
        if (random_value(rand_seed) < 0.03)
            Result[id.xy] = float4(0, 1, 0, 1);
        else
            Result[id.xy] = float4(0, 0, 0, 1);
        return;
    }
    else if (id.y == 0)
    {
        if (random_value(rand_seed) < 0.03)
            Result[id.xy] = float4(1, 0, 0, 1);
        else
            Result[id.xy] = float4(0, 0, 0, 1);        
        return;
    }
    float4 col_left = Input[id.xy - uint2(1, 0)];
    float4 col_bottom = Input[id.xy - uint2(0, 1)];
    if (yellow_pixel(Input, id.xy - uint2(1, 0)) || yellow_pixel(Input, id.xy - uint2(0, 1)) || 
        yellow_pixel(Input, id.xy + uint2(1, 0)) || yellow_pixel(Input, id.xy + uint2(0, 1)))
    {
        float v;
        v = max(max(yellow_color(Input, id.xy - uint2(1, 0)), yellow_color(Input, id.xy - uint2(0, 1))),
                max(yellow_color(Input, id.xy + uint2(1, 0)), yellow_color(Input, id.xy + uint2(0, 1))));
        Result[id.xy] = float4(v - 0.01, v - 0.01, 0, 1);
        return;
    }
    if (all(col_left == green) && all(col_bottom == red))
    {
        Result[id.xy] = yellow;
    }
    else if (all(col_left == green))
    {
        Result[id.xy] = green;
    }
    else if (all(col_bottom == red))
    {
        Result[id.xy] = red;
    }
    else
    {
        Result[id.xy] = float4(0, 0, 0, 1);
    }

// Result[id.xy] = Input[id.xy];
    // float4(0, (float) id.x / 2048, (float) id.y / 2048, 0);
    //Result[id.xy] = float4(id.x & id.y, (id.x & 15) / 15.0, (id.y & 15) / 15.0, 0.0);
}
